import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { ModeToggle } from "@/components/mode-toogle";
import { DotBackground } from "@/components/dot-background";
import { LiquidGlassCard } from "@/components/ui/liquid-glass-card";
import Footer from "@/components/sections/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="relative min-h-screen">
            {/* ================ Background ================ */}
            <DotBackground />

            {/* ================ Navbar Section ================ */}
            <LiquidGlassCard
              borderRadius="0px"
              shadowIntensity="none"
              glowIntensity="none"
              className="relevant col-span-2 p-6 bg-background/8 sticky top-0 z-50 w-full"
              draggable={false}
            >
              <div className="flex justify-between sticky top-0 z-20">
                <div className="flex items-center text-xl text-[#154091] font-bold">
                  <img
                    src={"/images/byte-logo-raw-nobg.png"}
                    className="h-12 w-12"
                    alt="BYTE Logo"
                  />
                  BYTE
                </div>

                <div className="flex gap-4 items-center">
                  <Navbar />
                  <ModeToggle />
                </div>
              </div>
            </LiquidGlassCard>

            {children}
          </div>

          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
