import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { ModeToggle } from "@/components/Mode-Toogle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >

          {/* ================ Navbar Section ================ */}
          <nav className="flex justify-between px-8 py-4">
            <div className="flex items-center text-xl text-[#154091] font-bold">
              <img
                src={"/images/byte-logo-raw-nobg.png"}
                className="h-12 w-12"
                alt="BYTE Logo"
              />
              BYTE
            </div>

            <div className="flex gap-4 items-center">
              <Navbar />
              <ModeToggle />
            </div>
          </nav>

          {children}

        </ThemeProvider>
      </body>
    </html>
  );
}
